image: gitpod/workspace-bun

tasks:
  - name: UseNode20
    command: |
      nvm i 20.9.0
      nvm use 20.9.0
      nvm alias default 20.9.0
      echo "nvm use default &>/dev/null" >> ~/.bashrc.d/51-nvm-fix

  - name: Init a bun project and run
    init: |
      # Init a project if needed
      if test ! -e package.json; then {
        bun init -y
      } fi
      # Install dependencies
      bun install
      
    command: |
      # Run project
      bun run dev

ports:
  - port: 3000
    onOpen: open-preview
